# Generated by Django 3.1.2 on 2020-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('whats_app_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('vk_url', models.URLField(blank=True, max_length=255, null=True)),
                ('insta_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
