# Generated by Django 3.1.2 on 2020-10-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='descrtion',
            new_name='description',
        ),
    ]
