# Generated by Django 3.1.2 on 2020-10-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_slide',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
