# Generated by Django 3.1.2 on 2020-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
