# Generated by Django 3.1.2 on 2020-10-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title', 'price')},
        ),
    ]
