# Generated by Django 3.1.2 on 2020-10-06 21:15

from django.db import migrations, models
import django.db.models.deletion
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201006_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cat',
            field=models.CharField(choices=[('glasses', 'glasses'), ('frames', 'frames'), ('outlet', 'outlet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='material',
            name='cat',
            field=models.CharField(choices=[('glasses', 'glasses'), ('frames', 'frames'), ('outlet', 'outlet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='opticalpower',
            name='cat',
            field=models.CharField(choices=[('glasses', 'glasses'), ('frames', 'frames'), ('outlet', 'outlet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalpower',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='radius',
            name='cat',
            field=models.CharField(choices=[('glasses', 'glasses'), ('frames', 'frames'), ('outlet', 'outlet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radius',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='volume',
            name='cat',
            field=models.CharField(choices=[('glasses', 'glasses'), ('frames', 'frames'), ('outlet', 'outlet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True, validators=[products.validators.min_0]),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
    ]
