# Generated by Django 3.1.2 on 2020-10-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201006_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='material',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='opticalpower',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='opticalpower',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='radius',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='radius',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='subcat',
        ),
    ]
