# Generated by Django 3.1.2 on 2020-10-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201006_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='opticalpower',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='radius',
            options={'ordering': ('value',)},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ('value',)},
        ),
    ]
