# Generated by Django 3.1.2 on 2020-10-19 13:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201014_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_file_path),
        ),
    ]
